name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  license-check:
    name: Check Dependency Licenses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build .env file
        run: |
          touch .env
          echo TXTX_DEV_NPM_READ_TOKEN="${{ secrets.TXTX_DEV_NPM_READ_TOKEN }}" >> .env

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm run ci

      - name: Check licenses
        run: |
          npx license-checker-rseidelsohn \
            --onlyAllow "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;0BSD;CC0-1.0;Unlicense;CC-BY-4.0;CC-BY-3.0;Python-2.0;BlueOak-1.0.0;MPL-2.0" \
            --excludePrivatePackages \
            --excludePackages "@metamask/eth-json-rpc-provider@1.0.1"

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build .env file
        run: |
          touch .env
          echo ID_SERVICE_URL="https://id.txtx.run/proxy" >> .env
          echo TXTX_DEV_NPM_READ_TOKEN="${{ secrets.TXTX_DEV_NPM_READ_TOKEN }}" >> .env
          cat .env

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm run ci
      - run: npm run build

      - name: Compress Build
        run: tar -zcvf txtx-web-ui.tar.gz dist

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: txtx-web-ui.tar.gz
          path: txtx-web-ui.tar.gz
